### ISSUE TITLE
Suggest removal of Fionn Kheller's Joi article from readme

### ISSUE THREAD

**Issue by iteles** [nelsonic/learn-hapi#30]
Because it now starts with the words:
> UPDATE: This guide is extremely outdated!

which doesn't look great for the tutorial :blush:

https://medium.com/the-spumko-suite/creating-validation-schemas-with-joi-eb4ff19f6688

**Comment by iteles** [comment]
Same thing with testing with Lab: https://medium.com/the-spumko-suite/testing-hapi-services-with-lab-96ac463c490a

**Comment by nelsonic** [comment]
Yes, tutorials which are not updated can be removed.
