### ISSUE TITLE
Number of tests in screenshots may be confusing?

### ISSUE THREAD

**Issue by iteles** [nelsonic/learn-hapi#34]
Currently in the readme there are 2 lab tests in total, but the screenshots are showing that [2 tests run after writing the basic http test](https://github.com/nelsonic/learn-hapi/blame/ede39c3934112b816e2df8567f8170b73132f993/README.md#L276) when only 1 has been written by following the tutorial and [3 tests after the boom section](https://github.com/nelsonic/learn-hapi/blame/ede39c3934112b816e2df8567f8170b73132f993/README.md#L342) when only 2 have been written (the one that teaches use of lab and the one that teaches boom).

If we think this might confuse people, I'm happy to replace them with these images (same but show 1 test first then 2 tests):
<img width="287" alt="screen shot 2015-09-26 at 21 26 19" src="https://cloud.githubusercontent.com/assets/4185328/10119715/6232f530-6495-11e5-86ef-17d2bd61795a.png">

<img width="809" alt="screen shot 2015-09-26 at 21 24 47" src="https://cloud.githubusercontent.com/assets/4185328/10119711/21c84fc2-6495-11e5-8d51-c6df5181e4f4.png">

**Comment by iteles** [comment]
@nelsonic Let me know if you want me to take care of this or if this isn't an issue and I'll close it.

**Comment by nelsonic** [comment]
Please do. :+1:
