### ISSUE TITLE
Uploading files in Hapi.

### ISSUE THREAD

**Issue by sohilpandya** [nelsonic/learn-hapi#39]
Both @mantagen and I have seen that you have got a hapi-upload module for file uploads. Does this mean that its not a built-in part of hapi? we are completing ex. 11 of makemehapi and found the answer to contain chunking, can you recommend any other alternatives or should we look into hapi-upload?

**Comment by nelsonic** [comment]
good question @sohilpandya ... are you *averse* to using [*chunking*](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) ?

**Comment by sohilpandya** [comment]
Not at all. I was looking into alternatives.

**Comment by nelsonic** [comment]
Ok. did you manage to complete the `makemehapi` exercises? 
as soon as you need to upload images/files for an MVP/App/Site *please* let me know. :+1:

**Comment by sohilpandya** [comment]
We are nearly done only 13 left. :open_mouth: 

Will let you know as soon as we need it for an MVP. :smile: 

Thanks!
