### ISSUE TITLE
Can't run the 'hello world' example

### ISSUE THREAD

**Issue by dakoo** [nelsonic/learn-hapi#7]
I tried to run the first sample code. However, it doesn't work with an error.
To fix this problem, I replaced 
  var server = new Hapi.Server('0.0.0.0', 3000);
with 
  var server = new Hapi.Server();
  server.connection({port : 3000});

I am using Windows 7 and node version is 0.10.36. I am not sure this issue results from the environment though.

**Comment by nelsonic** [comment]
Hi @dakoo 
thanks very much for your interest and for sharing your experience. 
I will investigate the issue shortly and get back to you. :+1:

**Comment by johncrosby** [comment]
I had same thing with ubuntu. dakoo's fix worked.

**Comment by nelsonic** [comment]
Hi @johncrosby please submit a PR with the change. thanks. :+1:

**Comment by nelsonic** [comment]
@dakoo I think this now works in hapi 8.8.0 please confirm. if not please re-open the issue.
